// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYbyGcGHE6SXriKb5AheJZ3jYb5Kb80IU',
    appId: '1:398290101750:web:df94374656ef58203053d7',
    messagingSenderId: '398290101750',
    projectId: 'adoptame-db',
    authDomain: 'adoptame-db.firebaseapp.com',
    storageBucket: 'adoptame-db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUu75QAiy7i7kDFOpEtAB-lDdRnRQD96Y',
    appId: '1:398290101750:android:2a0673a55ceecd5f3053d7',
    messagingSenderId: '398290101750',
    projectId: 'adoptame-db',
    storageBucket: 'adoptame-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLRLwSJkEGCjnVb66M2RQIFMNcKgZ7PBI',
    appId: '1:398290101750:ios:ff7f49d01ce9ca573053d7',
    messagingSenderId: '398290101750',
    projectId: 'adoptame-db',
    storageBucket: 'adoptame-db.appspot.com',
    iosBundleId: 'com.example.adoptme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLRLwSJkEGCjnVb66M2RQIFMNcKgZ7PBI',
    appId: '1:398290101750:ios:ff7f49d01ce9ca573053d7',
    messagingSenderId: '398290101750',
    projectId: 'adoptame-db',
    storageBucket: 'adoptame-db.appspot.com',
    iosBundleId: 'com.example.adoptme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYbyGcGHE6SXriKb5AheJZ3jYb5Kb80IU',
    appId: '1:398290101750:web:342deb0d4e0609113053d7',
    messagingSenderId: '398290101750',
    projectId: 'adoptame-db',
    authDomain: 'adoptame-db.firebaseapp.com',
    storageBucket: 'adoptame-db.appspot.com',
  );
}
